runtime: java11
env: standard
runtime_config:
  jdk: openjdk11
instance_class: B2
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
  - url: /.*
    script: this field is required, but ignored
basic_scaling:
  max_instances: 3